server:
  port: 8888
  
spring:
# buscar as config. no fileSystem
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations:
#          - /home/rtenorio/Documents/microservice-repo
        git:
          uri: https://github.com/RodrigoTenorio86/microservice-repo
          search-paths: fornecedor
            
        
          
